# Generated by Django 3.1.7 on 2021-03-08 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20210308_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(1, 'Cakes'), (2, 'Snacks'), (3, 'Pastry')], default=1, max_length=10),
        ),
    ]
