# Generated by Django 3.1.7 on 2021-03-08 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='p_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
