# Generated by Django 3.1.7 on 2021-03-08 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_p_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[(1, 'Cakes'), (2, 'Snacks'), (3, 'Pastry')], max_length=10, null=True),
        ),
    ]
