# Generated by Django 3.1.7 on 2021-03-08 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_auto_20210308_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CA', 'Cakes'), ('CO', 'Cookies'), ('PA', 'Pastries')], max_length=10, null=True),
        ),
    ]
