# Generated by Django 3.1.7 on 2021-03-09 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20210309_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Cakes', 'Cakes'), ('Snacks', 'Snacks'), ('Pastries', 'Pastries')], max_length=10, null=True),
        ),
    ]
