# Generated by Django 3.1.7 on 2021-03-11 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_auto_20210309_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='weight',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(default='Per kg', max_length=20),
        ),
    ]
